//...imports already there
import "./globals.css";
import type { Metadata } from "next";

//TOCHANGE
export const metadata : Metadata = {
    title: "Ecommerce Shop with 3D preview",
    description: "Generated by create next app",
};

//TOCHANGE
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth bg-stone-950">
      <body>
        {children}
      </body>
    </html>
  );
}
